Merge packages asynchronously in Portage.
This allows for the scheduler to continue to run while packages are
being merged and installed, allowing for additional parallelism and
making better use of the CPUs.

Review URL: http://codereview.chromium.org/6713043
(cherry picked from commit 7535cabdf2fab76fc55df83643157613dfd66be9)

Preserve elog message continuity during updates.

This integrates the fix from commit
8209aeab647b1ab80a64d5931069b3533776ef75 with the asynchronous merge
changes from commit 7535cabdf2fab76fc55df83643157613dfd66be9.
(cherry picked from commit f823031ed33bda9579d265b62607380bb255dfdd)

MergeProcess: Fix PORTAGE_BACKGROUND/LOG_FILE use

In this subprocess we don't want PORTAGE_BACKGROUND to suppress
stdout/stderr output since they are pipes. We also don't want to open
PORTAGE_LOG_FILE, since it will already be opened by the parent
process, so we set the PORTAGE_BACKGROUND="subprocess" value for use
in conditional logging code involving PORTAGE_LOG_FILE.
(cherry picked from commit 3081e651fc3cd3a0729bb1fbe2e93fbc58dcef0d)

MergeProcess: close elog_writer_fd leak
(cherry picked from commit 981f27f79e607877e7b8e47a904e3972d0e8336e)

ebuild(1): fix AttributeError for merge phase

  File "pym/portage/dbapi/vartree.py", line 4043, in merge
    merge_task.start()
  File "pym/_emerge/AsynchronousTask.py", line 23, in start
    self._start()
  File "pym/_emerge/SpawnProcess.py", line 118, in _start
    self._reg_id = self.scheduler.register(files.process.fileno(),
AttributeError: 'NoneType' object has no attribute 'register'
(cherry picked from commit f3c4a464cc38788a4946de5331c2618c183fccac)

MergeProcess: separate unmerge output from merge

The unmerge output has been mixed together with the merge output since
commit 7535cabdf2fab76fc55df83643157613dfd66be9 because
dblink._scheduler was set to None. Now it's fixed to produce separate
logs like it used to.
(cherry picked from commit 2fd76b639d44f3ff3624ed8dbe96d214a42875e5)

vartree: remove unused scheduler references

Since all the merge code runs inside MergeProcess now, there's no
reason to yield to the scheduler.
(cherry picked from commit 7ffa0683cd9c40e630488af5783c549bee5cd3c8)

dblink: fix elog bugs for unmerge phases
(cherry picked from commit fe6a9433426d284aabdf774376082fbed1741478)

MergeProcess: handle unicode in elog pipe
(cherry picked from commit 176e2c74b368c73b593553773e749b3f25ddad72)

vartree: remove broken scheduler reference
(cherry picked from commit 0c4d01435737ba71d9c628ee34849c36ecec140b)

MergeProcess: toggle vardbapi._pkgs_changed

dblink: use self.mycpv in _elog

MergeProcess: call elog_process for replaced pkgs

PackageMerge: call wait() for conformity

Reoranize PackageMerge/MergeListItem interaction.

unmerge: fix PORTAGE_BACKGROUND logic

MergeProcess: relocate portage reinstall code

This code goes inside _start since it needs to execute in the parent
process.

MergeProcess: query blockers in the main process

Metadata cache queries may not work for some databases from within a
subprocess. For example, sqlite is known to misbehave.

MergeProcess: add fallback setcpv call

It's important that this metadata access happens in the parent process,
since closing of file descriptors in the subprocess can prevent access
to open database connections such as that used by the sqlite metadata
cache module.

dblink: rename 'buffer' var in _elog_process

Avoid name collision with built-in 'buffer' function.

Change-Id: Ic06b5c684ad41ff7a0aba08cd24b2548fd8e247e

vardbapi: disable subprocess vdb cache updates

Since commit 7535cabdf2fab76fc55df83643157613dfd66be9,
vardbapi.flush_cache() is often called within subprocesses spawned
from MergeProcess. The _aux_cache_threshold doesn't work as designed
if the cache is flushed from a subprocess like this, can lead to the
vdb cache being flushed for every single merge. This is a waste of
disk IO, so disable vdb cache updates in subprocesses.
(cherry picked from commit a983fc1c83402dbfe0a423bf729c72eeb795388c)